import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="tr">
      <body className="antialiased">
        {/*  Navigasyon */}
        <Nav />

        {/* İçerik */}
        <main className="container mx-auto">{children}</main>

        {/* Footer */}
      </body>
    </html >
  );
}
